# Site settings
title: islamuthentic
email: islamuthentic@tutanota.de
description: > # this means to ignore newlines until "baseurl:"
  just an awesome weblog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "islamuthentic.github.io" # the base hostname & protocol for your site
twitter_username: islamuthentic
github_username:  islamuthentic

# Build settings
markdown: kramdown
